# A config.toml file is required for every Supabase project

[api]
# Port to use for the API URL
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API endpoints
# public and storage are always included
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search_path of every request. public is always included
extra_search_path = ["public", "extensions"]
# The maximum number of rows returned from a view, table, or stored procedure. Limits payload size for accidental or malicious requests
max_rows = 1000

[db]
# Port to use for the local database URL
port = 54322
# The database major version to use
major_version = 15

[studio]
# Port to use for Supabase Studio
port = 54323

[inbucket]
# Port to use for the email testing server
port = 54324

[storage]
# The maximum file size allowed (10MB)
file_size_limit = "10MiB"

[auth]
# The base URL of your website
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth will accept as redirect destinations
additional_redirect_urls = ["https://localhost:3000"]
# How long tokens are valid for, in seconds
jwt_expiry = 3600
# Allow/disallow new user signups to your project
enable_signup = true

[auth.email]
# Allow/disallow new user signups via email to your project
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old and new email addresses
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in
enable_confirmations = false

# Configure email template
[auth.email.template.invite]
subject = "You have been invited"
# content_path = "./supabase/templates/invite.html"  # Commented out - template file not needed

# Edge Functions configuration - SECURITY FIX
# NOTE: Global verify_jwt not supported, must be set per function
# Default behavior: JWT verification enabled (secure by default)

[functions.email_inbox]
# Disable JWT verification for webhook endpoints only
verify_jwt = false
