include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - lib/generated_plugin_registrant.dart
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # Project-specific additions beyond flutter_lints defaults
    avoid_returning_null_for_future: true
    avoid_slow_async_io: true
    prefer_single_quotes: true
