include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - lib/generated_plugin_registrant.dart
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    # Demote less critical lints to info or suppress
    avoid_print: info
    avoid_slow_async_io: info
    use_build_context_synchronously: info
    dead_null_aware_expression: info
    unnecessary_null_comparison: info
    unreachable_switch_default: ignore
    # Keep important ones as errors
    invalid_use_of_protected_member: error
    invalid_use_of_visible_for_testing_member: error

linter:
  rules:
    # Project-specific additions beyond flutter_lints defaults
    avoid_returning_null_for_future: true
    avoid_slow_async_io: false  # Too many false positives
    prefer_single_quotes: true
    # Disable overly strict rules for this codebase
    use_build_context_synchronously: false
    avoid_print: false  # Allow in dev, will be removed before production
