// Mocks generated by Mockito 5.4.6 from annotations
// in duru_notes/test/services/audio_recording_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i7;

import 'package:duru_notes/core/monitoring/app_logger.dart' as _i2;
import 'package:duru_notes/models/note_block.dart' as _i6;
import 'package:duru_notes/services/analytics/analytics_service.dart' as _i4;
import 'package:duru_notes/services/attachment_service.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AppLogger].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLogger extends _i1.Mock implements _i2.AppLogger {
  MockAppLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void debug(String? message, {Map<String, dynamic>? data}) =>
      super.noSuchMethod(
        Invocation.method(#debug, [message], {#data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void info(String? message, {Map<String, dynamic>? data}) =>
      super.noSuchMethod(
        Invocation.method(#info, [message], {#data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void warning(String? message, {Map<String, dynamic>? data}) =>
      super.noSuchMethod(
        Invocation.method(#warning, [message], {#data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void warn(String? message, {Map<String, dynamic>? data}) =>
      super.noSuchMethod(
        Invocation.method(#warn, [message], {#data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void error(
    String? message, {
    Object? error,
    StackTrace? stackTrace,
    Map<String, dynamic>? data,
  }) => super.noSuchMethod(
    Invocation.method(
      #error,
      [message],
      {#error: error, #stackTrace: stackTrace, #data: data},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void breadcrumb(String? message, {Map<String, dynamic>? data}) =>
      super.noSuchMethod(
        Invocation.method(#breadcrumb, [message], {#data: data}),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> flush() =>
      (super.noSuchMethod(
            Invocation.method(#flush, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [AnalyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsService extends _i1.Mock implements _i4.AnalyticsService {
  MockAnalyticsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isEnabled =>
      (super.noSuchMethod(Invocation.getter(#isEnabled), returnValue: false)
          as bool);

  @override
  void startTiming(String? eventName) => super.noSuchMethod(
    Invocation.method(#startTiming, [eventName]),
    returnValueForMissingStub: null,
  );

  @override
  void endTiming(String? eventName, {Map<String, dynamic>? properties}) =>
      super.noSuchMethod(
        Invocation.method(#endTiming, [eventName], {#properties: properties}),
        returnValueForMissingStub: null,
      );

  @override
  void featureUsed(String? featureName, {Map<String, dynamic>? properties}) =>
      super.noSuchMethod(
        Invocation.method(
          #featureUsed,
          [featureName],
          {#properties: properties},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void trackError(
    String? message, {
    String? context,
    Map<String, dynamic>? properties,
  }) => super.noSuchMethod(
    Invocation.method(
      #trackError,
      [message],
      {#context: context, #properties: properties},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void event(String? name, {Map<String, dynamic>? properties}) =>
      super.noSuchMethod(
        Invocation.method(#event, [name], {#properties: properties}),
        returnValueForMissingStub: null,
      );

  @override
  void enable() => super.noSuchMethod(
    Invocation.method(#enable, []),
    returnValueForMissingStub: null,
  );

  @override
  void disable() => super.noSuchMethod(
    Invocation.method(#disable, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AttachmentService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAttachmentService extends _i1.Mock implements _i5.AttachmentService {
  MockAttachmentService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i6.AttachmentBlockData?> pickAndUpload() =>
      (super.noSuchMethod(
            Invocation.method(#pickAndUpload, []),
            returnValue: _i3.Future<_i6.AttachmentBlockData?>.value(),
          )
          as _i3.Future<_i6.AttachmentBlockData?>);

  @override
  _i3.Future<_i6.AttachmentBlockData?> uploadFromBytes({
    required _i7.Uint8List? bytes,
    required String? filename,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadFromBytes, [], {
              #bytes: bytes,
              #filename: filename,
            }),
            returnValue: _i3.Future<_i6.AttachmentBlockData?>.value(),
          )
          as _i3.Future<_i6.AttachmentBlockData?>);

  @override
  _i3.Future<_i7.Uint8List?> download(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#download, [url]),
            returnValue: _i3.Future<_i7.Uint8List?>.value(),
          )
          as _i3.Future<_i7.Uint8List?>);

  @override
  _i3.Future<bool> delete(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [url]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  bool isSupported(String? mimeType) =>
      (super.noSuchMethod(
            Invocation.method(#isSupported, [mimeType]),
            returnValue: false,
          )
          as bool);
}
