// Mocks generated by Mockito 5.4.6 from annotations
// in duru_notes/test/services/lazy_encryption_race_condition_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:typed_data' as _i13;

import 'package:duru_notes/core/crypto/crypto_box.dart' as _i3;
import 'package:flutter_local_notifications/src/flutter_local_notifications_plugin.dart'
    as _i5;
import 'package:flutter_local_notifications/src/initialization_settings.dart'
    as _i7;
import 'package:flutter_local_notifications/src/notification_details.dart'
    as _i9;
import 'package:flutter_local_notifications/src/platform_specifics/android/schedule_mode.dart'
    as _i11;
import 'package:flutter_local_notifications/src/types.dart' as _i12;
import 'package:flutter_local_notifications_platform_interface/flutter_local_notifications_platform_interface.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:riverpod/src/internals.dart' as _i2;
import 'package:timezone/timezone.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProviderContainer_0 extends _i1.SmartFake
    implements _i2.ProviderContainer {
  _FakeProviderContainer_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeKeepAliveLink_1 extends _i1.SmartFake implements _i2.KeepAliveLink {
  _FakeKeepAliveLink_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProviderSubscription_2<State1> extends _i1.SmartFake
    implements _i2.ProviderSubscription<State1> {
  _FakeProviderSubscription_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDecryptResult_3<T> extends _i1.SmartFake
    implements _i3.DecryptResult<T> {
  _FakeDecryptResult_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [Ref].
///
/// See the documentation for Mockito's code generation for more information.
class MockRef<State extends Object?> extends _i1.Mock
    implements _i2.Ref<State> {
  @override
  _i2.ProviderContainer get container =>
      (super.noSuchMethod(
            Invocation.getter(#container),
            returnValue: _FakeProviderContainer_0(
              this,
              Invocation.getter(#container),
            ),
            returnValueForMissingStub: _FakeProviderContainer_0(
              this,
              Invocation.getter(#container),
            ),
          )
          as _i2.ProviderContainer);

  @override
  T refresh<T>(_i2.Refreshable<T>? provider) =>
      (super.noSuchMethod(
            Invocation.method(#refresh, [provider]),
            returnValue: _i4.dummyValue<T>(
              this,
              Invocation.method(#refresh, [provider]),
            ),
            returnValueForMissingStub: _i4.dummyValue<T>(
              this,
              Invocation.method(#refresh, [provider]),
            ),
          )
          as T);

  @override
  void invalidate(_i2.ProviderOrFamily? provider) => super.noSuchMethod(
    Invocation.method(#invalidate, [provider]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  void listenSelf(
    void Function(State?, State)? listener, {
    void Function(Object, StackTrace)? onError,
  }) => super.noSuchMethod(
    Invocation.method(#listenSelf, [listener], {#onError: onError}),
    returnValueForMissingStub: null,
  );

  @override
  void invalidateSelf() => super.noSuchMethod(
    Invocation.method(#invalidateSelf, []),
    returnValueForMissingStub: null,
  );

  @override
  void onAddListener(void Function()? cb) => super.noSuchMethod(
    Invocation.method(#onAddListener, [cb]),
    returnValueForMissingStub: null,
  );

  @override
  void onRemoveListener(void Function()? cb) => super.noSuchMethod(
    Invocation.method(#onRemoveListener, [cb]),
    returnValueForMissingStub: null,
  );

  @override
  void onResume(void Function()? cb) => super.noSuchMethod(
    Invocation.method(#onResume, [cb]),
    returnValueForMissingStub: null,
  );

  @override
  void onCancel(void Function()? cb) => super.noSuchMethod(
    Invocation.method(#onCancel, [cb]),
    returnValueForMissingStub: null,
  );

  @override
  void onDispose(void Function()? cb) => super.noSuchMethod(
    Invocation.method(#onDispose, [cb]),
    returnValueForMissingStub: null,
  );

  @override
  T read<T>(_i2.ProviderListenable<T>? provider) =>
      (super.noSuchMethod(
            Invocation.method(#read, [provider]),
            returnValue: _i4.dummyValue<T>(
              this,
              Invocation.method(#read, [provider]),
            ),
            returnValueForMissingStub: _i4.dummyValue<T>(
              this,
              Invocation.method(#read, [provider]),
            ),
          )
          as T);

  @override
  bool exists(_i2.ProviderBase<Object?>? provider) =>
      (super.noSuchMethod(
            Invocation.method(#exists, [provider]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  T watch<T>(_i2.ProviderListenable<T>? provider) =>
      (super.noSuchMethod(
            Invocation.method(#watch, [provider]),
            returnValue: _i4.dummyValue<T>(
              this,
              Invocation.method(#watch, [provider]),
            ),
            returnValueForMissingStub: _i4.dummyValue<T>(
              this,
              Invocation.method(#watch, [provider]),
            ),
          )
          as T);

  @override
  _i2.KeepAliveLink keepAlive() =>
      (super.noSuchMethod(
            Invocation.method(#keepAlive, []),
            returnValue: _FakeKeepAliveLink_1(
              this,
              Invocation.method(#keepAlive, []),
            ),
            returnValueForMissingStub: _FakeKeepAliveLink_1(
              this,
              Invocation.method(#keepAlive, []),
            ),
          )
          as _i2.KeepAliveLink);

  @override
  _i2.ProviderSubscription<T> listen<T>(
    _i2.ProviderListenable<T>? provider,
    void Function(T?, T)? listener, {
    void Function(Object, StackTrace)? onError,
    bool? fireImmediately,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #listen,
              [provider, listener],
              {#onError: onError, #fireImmediately: fireImmediately},
            ),
            returnValue: _FakeProviderSubscription_2<T>(
              this,
              Invocation.method(
                #listen,
                [provider, listener],
                {#onError: onError, #fireImmediately: fireImmediately},
              ),
            ),
            returnValueForMissingStub: _FakeProviderSubscription_2<T>(
              this,
              Invocation.method(
                #listen,
                [provider, listener],
                {#onError: onError, #fireImmediately: fireImmediately},
              ),
            ),
          )
          as _i2.ProviderSubscription<T>);
}

/// A class which mocks [FlutterLocalNotificationsPlugin].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterLocalNotificationsPlugin extends _i1.Mock
    implements _i5.FlutterLocalNotificationsPlugin {
  @override
  _i6.Future<bool?> initialize(
    _i7.InitializationSettings? initializationSettings, {
    _i8.DidReceiveNotificationResponseCallback?
    onDidReceiveNotificationResponse,
    _i8.DidReceiveBackgroundNotificationResponseCallback?
    onDidReceiveBackgroundNotificationResponse,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #initialize,
              [initializationSettings],
              {
                #onDidReceiveNotificationResponse:
                    onDidReceiveNotificationResponse,
                #onDidReceiveBackgroundNotificationResponse:
                    onDidReceiveBackgroundNotificationResponse,
              },
            ),
            returnValue: _i6.Future<bool?>.value(),
            returnValueForMissingStub: _i6.Future<bool?>.value(),
          )
          as _i6.Future<bool?>);

  @override
  _i6.Future<_i8.NotificationAppLaunchDetails?>
  getNotificationAppLaunchDetails() =>
      (super.noSuchMethod(
            Invocation.method(#getNotificationAppLaunchDetails, []),
            returnValue: _i6.Future<_i8.NotificationAppLaunchDetails?>.value(),
            returnValueForMissingStub:
                _i6.Future<_i8.NotificationAppLaunchDetails?>.value(),
          )
          as _i6.Future<_i8.NotificationAppLaunchDetails?>);

  @override
  _i6.Future<void> show(
    int? id,
    String? title,
    String? body,
    _i9.NotificationDetails? notificationDetails, {
    String? payload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #show,
              [id, title, body, notificationDetails],
              {#payload: payload},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> cancel(int? id, {String? tag}) =>
      (super.noSuchMethod(
            Invocation.method(#cancel, [id], {#tag: tag}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> cancelAll() =>
      (super.noSuchMethod(
            Invocation.method(#cancelAll, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> cancelAllPendingNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#cancelAllPendingNotifications, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> zonedSchedule(
    int? id,
    String? title,
    String? body,
    _i10.TZDateTime? scheduledDate,
    _i9.NotificationDetails? notificationDetails, {
    required _i11.AndroidScheduleMode? androidScheduleMode,
    String? payload,
    _i12.DateTimeComponents? matchDateTimeComponents,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #zonedSchedule,
              [id, title, body, scheduledDate, notificationDetails],
              {
                #androidScheduleMode: androidScheduleMode,
                #payload: payload,
                #matchDateTimeComponents: matchDateTimeComponents,
              },
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> periodicallyShow(
    int? id,
    String? title,
    String? body,
    _i8.RepeatInterval? repeatInterval,
    _i9.NotificationDetails? notificationDetails, {
    required _i11.AndroidScheduleMode? androidScheduleMode,
    String? payload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #periodicallyShow,
              [id, title, body, repeatInterval, notificationDetails],
              {#androidScheduleMode: androidScheduleMode, #payload: payload},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> periodicallyShowWithDuration(
    int? id,
    String? title,
    String? body,
    Duration? repeatDurationInterval,
    _i9.NotificationDetails? notificationDetails, {
    _i11.AndroidScheduleMode? androidScheduleMode =
        _i11.AndroidScheduleMode.exact,
    String? payload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #periodicallyShowWithDuration,
              [id, title, body, repeatDurationInterval, notificationDetails],
              {#androidScheduleMode: androidScheduleMode, #payload: payload},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i8.PendingNotificationRequest>>
  pendingNotificationRequests() =>
      (super.noSuchMethod(
            Invocation.method(#pendingNotificationRequests, []),
            returnValue: _i6.Future<List<_i8.PendingNotificationRequest>>.value(
              <_i8.PendingNotificationRequest>[],
            ),
            returnValueForMissingStub:
                _i6.Future<List<_i8.PendingNotificationRequest>>.value(
                  <_i8.PendingNotificationRequest>[],
                ),
          )
          as _i6.Future<List<_i8.PendingNotificationRequest>>);

  @override
  _i6.Future<List<_i8.ActiveNotification>> getActiveNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveNotifications, []),
            returnValue: _i6.Future<List<_i8.ActiveNotification>>.value(
              <_i8.ActiveNotification>[],
            ),
            returnValueForMissingStub:
                _i6.Future<List<_i8.ActiveNotification>>.value(
                  <_i8.ActiveNotification>[],
                ),
          )
          as _i6.Future<List<_i8.ActiveNotification>>);
}

/// A class which mocks [CryptoBox].
///
/// See the documentation for Mockito's code generation for more information.
class MockCryptoBox extends _i1.Mock implements _i3.CryptoBox {
  @override
  _i6.Future<_i13.Uint8List> encryptJsonForNote({
    required String? userId,
    required String? noteId,
    required Map<String, dynamic>? json,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#encryptJsonForNote, [], {
              #userId: userId,
              #noteId: noteId,
              #json: json,
            }),
            returnValue: _i6.Future<_i13.Uint8List>.value(_i13.Uint8List(0)),
            returnValueForMissingStub: _i6.Future<_i13.Uint8List>.value(
              _i13.Uint8List(0),
            ),
          )
          as _i6.Future<_i13.Uint8List>);

  @override
  _i6.Future<Map<String, dynamic>> decryptJsonForNote({
    required String? userId,
    required String? noteId,
    required _i13.Uint8List? data,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#decryptJsonForNote, [], {
              #userId: userId,
              #noteId: noteId,
              #data: data,
            }),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<_i13.Uint8List> encryptStringForNote({
    required String? userId,
    required String? noteId,
    required String? text,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#encryptStringForNote, [], {
              #userId: userId,
              #noteId: noteId,
              #text: text,
            }),
            returnValue: _i6.Future<_i13.Uint8List>.value(_i13.Uint8List(0)),
            returnValueForMissingStub: _i6.Future<_i13.Uint8List>.value(
              _i13.Uint8List(0),
            ),
          )
          as _i6.Future<_i13.Uint8List>);

  @override
  _i6.Future<String> decryptStringForNote({
    required String? userId,
    required String? noteId,
    required _i13.Uint8List? data,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#decryptStringForNote, [], {
              #userId: userId,
              #noteId: noteId,
              #data: data,
            }),
            returnValue: _i6.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#decryptStringForNote, [], {
                  #userId: userId,
                  #noteId: noteId,
                  #data: data,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#decryptStringForNote, [], {
                  #userId: userId,
                  #noteId: noteId,
                  #data: data,
                }),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<_i3.DecryptResult<Map<String, dynamic>>>
  decryptJsonForNoteWithFallback({
    required String? userId,
    required String? noteId,
    required _i13.Uint8List? data,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#decryptJsonForNoteWithFallback, [], {
              #userId: userId,
              #noteId: noteId,
              #data: data,
            }),
            returnValue:
                _i6.Future<_i3.DecryptResult<Map<String, dynamic>>>.value(
                  _FakeDecryptResult_3<Map<String, dynamic>>(
                    this,
                    Invocation.method(#decryptJsonForNoteWithFallback, [], {
                      #userId: userId,
                      #noteId: noteId,
                      #data: data,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i6.Future<_i3.DecryptResult<Map<String, dynamic>>>.value(
                  _FakeDecryptResult_3<Map<String, dynamic>>(
                    this,
                    Invocation.method(#decryptJsonForNoteWithFallback, [], {
                      #userId: userId,
                      #noteId: noteId,
                      #data: data,
                    }),
                  ),
                ),
          )
          as _i6.Future<_i3.DecryptResult<Map<String, dynamic>>>);

  @override
  _i6.Future<_i3.DecryptResult<String>> decryptStringForNoteWithFallback({
    required String? userId,
    required String? noteId,
    required _i13.Uint8List? data,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#decryptStringForNoteWithFallback, [], {
              #userId: userId,
              #noteId: noteId,
              #data: data,
            }),
            returnValue: _i6.Future<_i3.DecryptResult<String>>.value(
              _FakeDecryptResult_3<String>(
                this,
                Invocation.method(#decryptStringForNoteWithFallback, [], {
                  #userId: userId,
                  #noteId: noteId,
                  #data: data,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i3.DecryptResult<String>>.value(
                  _FakeDecryptResult_3<String>(
                    this,
                    Invocation.method(#decryptStringForNoteWithFallback, [], {
                      #userId: userId,
                      #noteId: noteId,
                      #data: data,
                    }),
                  ),
                ),
          )
          as _i6.Future<_i3.DecryptResult<String>>);
}
