// Mocks generated by Mockito 5.4.6 from annotations
// in duru_notes/test/services/permission_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:duru_notes/core/feature_flags.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FeatureFlags].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeatureFlags extends _i1.Mock implements _i2.FeatureFlags {
  MockFeatureFlags() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get enableUserIdFiltering =>
      (super.noSuchMethod(
            Invocation.getter(#enableUserIdFiltering),
            returnValue: false,
          )
          as bool);

  @override
  bool get useNewBlockEditor =>
      (super.noSuchMethod(
            Invocation.getter(#useNewBlockEditor),
            returnValue: false,
          )
          as bool);

  @override
  bool get useRefactoredComponents =>
      (super.noSuchMethod(
            Invocation.getter(#useRefactoredComponents),
            returnValue: false,
          )
          as bool);

  @override
  bool get useUnifiedPermissionManager =>
      (super.noSuchMethod(
            Invocation.getter(#useUnifiedPermissionManager),
            returnValue: false,
          )
          as bool);

  @override
  bool get useBlockEditorForNotes =>
      (super.noSuchMethod(
            Invocation.getter(#useBlockEditorForNotes),
            returnValue: false,
          )
          as bool);

  @override
  bool get enableAutomaticTrashPurge =>
      (super.noSuchMethod(
            Invocation.getter(#enableAutomaticTrashPurge),
            returnValue: false,
          )
          as bool);

  @override
  bool isEnabled(String? flagName) =>
      (super.noSuchMethod(
            Invocation.method(#isEnabled, [flagName]),
            returnValue: false,
          )
          as bool);

  @override
  bool isEnabledForUser(String? flagName, {String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#isEnabledForUser, [flagName], {#userId: userId}),
            returnValue: false,
          )
          as bool);

  @override
  void setOverride(String? flagName, bool? value) => super.noSuchMethod(
    Invocation.method(#setOverride, [flagName, value]),
    returnValueForMissingStub: null,
  );

  @override
  void clearOverrides() => super.noSuchMethod(
    Invocation.method(#clearOverrides, []),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<void> updateFromRemoteConfig() =>
      (super.noSuchMethod(
            Invocation.method(#updateFromRemoteConfig, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void setRolloutPercentage(String? flagName, double? percentage) =>
      super.noSuchMethod(
        Invocation.method(#setRolloutPercentage, [flagName, percentage]),
        returnValueForMissingStub: null,
      );

  @override
  bool enableUserIdFilteringFor(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#enableUserIdFilteringFor, [userId]),
            returnValue: false,
          )
          as bool);
}
