name: duru_notes
description: "Duru Notes - Your intelligent, secure note-taking companion with advanced reminders, voice transcription, and OCR scanning capabilities."
publish_to: 'none'

version: 1.0.0+1

# App metadata for store deployment
homepage: https://durunotes.app
repository: https://github.com/durunotes/duru-notes
issue_tracker: https://github.com/durunotes/duru-notes/issues
documentation: https://durunotes.app/docs

environment:
  sdk: ^3.9.0
  flutter: ">=3.9.0"

dependencies:
  cryptography: ^2.7.0
  cupertino_icons: ^1.0.8
  drift: ^2.28.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_markdown: ^0.7.7+1
  intl: ^0.20.2
  file_picker: ^10.3.1   # dosya seçimi için
  crypto: ^3.0.6         # SHA-256 hesaplamak için
  image_picker: ^1.2.0
  google_mlkit_text_recognition: ^0.10.0
  permission_handler: ^12.0.1
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  timezone: ^0.10.1
  flutter_timezone: ^4.1.1
  path: ^1.9.1
  path_provider: ^2.1.5
  receive_sharing_intent: ^1.4.5  # Android share sheet integration
  riverpod: ^2.6.1
  shared_preferences: ^2.5.3
  sqlite3_flutter_libs: ^0.5.39
  supabase_flutter: ^2.9.1
  url_launcher: ^6.3.2
  uuid: ^4.5.1
  sentry_flutter: ^9.6.0
  cached_network_image: ^3.3.1
  speech_to_text: ^7.3.0
  battery_plus: ^6.0.2
  device_info_plus: ^11.5.0
  flutter_local_notifications: ^19.4.1
  xml: ^6.3.0  # XML parsing for ENEX import
  geolocator: ^14.0.2
  geofence_service: ^6.0.0
  record: ^6.1.0  # Audio recording
  pdf: ^3.11.1  # PDF generation
  printing: ^5.12.0  # PDF printing and sharing
  share_plus: ^11.1.0  # Cross-platform sharing
  open_file: ^3.5.3  # Open files with system apps
  adapty_flutter: ^3.10.0  # Subscription management and monetization
  package_info_plus: ^8.0.2  # App version and build info

dev_dependencies:
  sentry_dart_plugin: ^3.1.1
  build_runner: ^2.6.0
  drift_dev: ^2.28.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.0
  integration_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  json_serializable: ^6.10.0
  mockito: ^5.4.4
  very_good_analysis: ^9.0.0
  image: ^4.1.7
  intl_utils: ^2.8.7

# Configuration for flutter_launcher_icons package
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "design/app_icon.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/env/
    - docs/

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: durunotes
  org: fittechs
